// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb5f5CNPaa2cQfgjmGEhiSyiNEKLfMup4',
    appId: '1:698398233958:web:6dedc6d3b090648d86e4a7',
    messagingSenderId: '698398233958',
    projectId: 'gorcery-b8793',
    authDomain: 'gorcery-b8793.firebaseapp.com',
    storageBucket: 'gorcery-b8793.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ6svvJdxqCGmME-DMvl3WmYtxg7DRKJg',
    appId: '1:698398233958:android:203aca3b4c714f4586e4a7',
    messagingSenderId: '698398233958',
    projectId: 'gorcery-b8793',
    storageBucket: 'gorcery-b8793.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa2ICCJUQ-Jkq_oPX0xOEFj9z8g1UgsO0',
    appId: '1:698398233958:ios:be376cf98379bbc686e4a7',
    messagingSenderId: '698398233958',
    projectId: 'gorcery-b8793',
    storageBucket: 'gorcery-b8793.appspot.com',
    iosBundleId: 'com.example.grocery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa2ICCJUQ-Jkq_oPX0xOEFj9z8g1UgsO0',
    appId: '1:698398233958:ios:be376cf98379bbc686e4a7',
    messagingSenderId: '698398233958',
    projectId: 'gorcery-b8793',
    storageBucket: 'gorcery-b8793.appspot.com',
    iosBundleId: 'com.example.grocery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb5f5CNPaa2cQfgjmGEhiSyiNEKLfMup4',
    appId: '1:698398233958:web:739df8c05c48628786e4a7',
    messagingSenderId: '698398233958',
    projectId: 'gorcery-b8793',
    authDomain: 'gorcery-b8793.firebaseapp.com',
    storageBucket: 'gorcery-b8793.appspot.com',
  );
}
